" GVIMRC

set hidden
set hlsearch
set number
set tabstop=4
set noexpandtab
set shiftwidth=4
set wrap
set autoindent
set backspace=indent,eol,start
set nocompatible
filetype plugin on
syntax on

" COLORS
autocmd BufEnter * :syntax sync fromstart

set background=dark
colorscheme solarized
set cursorline
hi cursorline 

set guifont=Fira Code:h12
set lines=40
set columns=100


