"" VIMRC
"" Modified: 2018-02-27

set hidden
set hlsearch
set incsearch
set lazyredraw
set magic
set number
set numberwidth=3
set tabstop=4
set noexpandtab
set shiftwidth=4
set foldcolumn=1
set wrap
set autoindent
set backspace=indent,eol,start
set nocompatible
set noswapfile
set spell
set spelllang=en_us
filetype plugin on
filetype indent on
set ai
set si
set autoread
set wildmenu
set ruler
set cursorline
set cursorcolumn
syntax on

"" COLORS

" HIGHLIGHTING
autocmd BufEnter * :syntax sync fromstart

syntax enable
set background=dark

try
    colorscheme nord
catch
endtry

set cmdheight=2

"" SHELL
let $SHELL='/bin/bash'

"" VIMHOME
if !$VIMHOME
	let $VIMHOME=$HOME."/.vim"
endif

"" SETTINGS
source $VIMHOME/pack/settings/nord.vim
source $VIMHOME/pack/settings/mappings.vim
source $VIMHOME/pack/settings/lightline.vim
source $VIMHOME/pack/settings/limelight.vim
source $VIMHOME/pack/settings/goyo.vim
source $VIMHOME/pack/settings/vim-gitgutter.vim
source $VIMHOME/pack/settings/YUNOcommit.vim
"source $VIMHOME/pack/settings/myHighlights.vim
source $VIMHOME/ftplugins/python/ipy.vim

"source $VIMHOME/colors/kalisi.vim
"source $VIMHOME/pack/plugins/start/airlines-themes.vim


"" DICTIONARIES

" ss toggles spelling
map <leader>ss :setlocal spell!<cr>


"" MOUSE
if has ('mouse')
	set mouse=a
endif

" When File is Reopened go to Last Position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif


" Always Show Status Line
set laststatus=2

" Format the Status Line
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c

" Quick Open Scratchpad Buffer
map <leader>q :e ~/buffer<cr>
