" VIMRC

set hidden
set hlsearch
set number
set numberwidth=3
set tabstop=4
set noexpandtab
set shiftwidth=4
set wrap
set autoindent
set backspace=indent,eol,start
set nocompatible
set noswapfile
set spell
set spelllang=en_us
filetype plugin on
syntax on

" COLORS
autocmd BufEnter * :syntax sync fromstart

autocmd BufNewFile,BufReadPost *.md set filetype=markdown
let g:markdown_fenced_languages = ['html', 'javascript', 'yaml', 'yml', 'coffee', 'json', 'diff', 'python', 'bash=sh', 'latex=tex', 'bibtex=bib', 'ruby=rb']
let g:markdown_minlines = 100
au FileType markdown setlocal textwidth=80

" Jekyll Front Matter Syntax Highlighting Fix
au BufNewFile,BufRead,BufWrite *.md syntax match Comment /\%^---\_.\{-}---$/


set background=dark
colorscheme solarized
set cursorline
hi cursorline ctermbg=245 ctermfg=49
set cursorcolumn
hi cursorcolumn ctermbg=245 ctermfg=49




" VIMHOME
if !$VIMHOME
    let $VIMHOME=$HOME."/.vim"
endif

if has('termguicolors')
	set termguicolors
	colorscheme solarized
endif



" SOURCES
source $VIMHOME/filetype.vim
source $VIMHOME/pack/settings/YUNOcommit.vim
source $VIMHOME/pack/settings/airline.vim
source $VIMHOME/pack/settings/mappings.vim
source $VIMHOME/pack/settings/templates.vim
source $VIMHOME/pack/settings/startify.vim


" DICTIONARY
"source dictionary+='/Users/Em/.vim/dictionaries'

" WILDMENU
set wildmenu
set wildmode=list:longest,full

" MOUSE
if has('mouse')
    set mouse=a
endif

" SEARCH
set incsearch


" STATUSBAR
set laststatus=2

let g:airline_theme="solarized"
" Airline Stuff
"let g:airline_left_sep = '📉'
let g:airline_left_sep = '🐹 '
"let g:airline_right_alt_sep = '📈'
let g:airline_right_sep = '🐹'


" Jekyll
let g:jekyll_path="/Users/Em/Repos/Page/pathologicalhandwaving.github.io"

" Align GitHub-flavored Markdown tables
au FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>


