#!/usr/bin/env ruby
require "yaml"

config_file = ENV['HOME'] + "/.config/custom-icons.yaml"

if File.exists?(config_file)
  yaml = YAML.load_file(config_file)
else
  File.open(config_file, "w"){|file| file << "Applications:\n  -\n    app: APPNAME\n    icon: ICONPATH"}
  %x[$EDITOR #{config_file}]
end

yaml["Applications"].each do |application|
  app = "/Applications/#{application['app']}.app"
  icon = application["icon"]
  puts %x[rm -rf #{app}/Icon\r]
  puts %x[sips -i #{icon} > /dev/null]
  puts %x[DeRez -only icns #{icon} > /tmp/icns.rsrc]
  puts %x[Rez -append /tmp/icns.rsrc -o #{app}/Icon\r]
  puts %x[SetFile -a C #{app}]
  puts %x[SetFile -a V #{app}/Icon\r]
end


