" VIMRC

set hidden
set hlsearch
set number
set numberwidth=3
set tabstop=4
set noexpandtab
set shiftwidth=4
set wrap
set autoindent
set backspace=indent,eol,start
set nocompatible
set noswapfile
set spell
set spelllang=en_us
filetype plugin on
syntax on

" COLORS
autocmd BufEnter * :syntax sync fromstart

syntax enable
set background=dark
colorscheme gruvbox
set cursorline
hi cursorline ctermbg=233 ctermfg=196
set cursorcolumn
hi cursorcolumn ctermbg=236 ctermfg=196


"" Shell
let $SHELL='/bin/bash'

" Markdown Crap
"autocmd BufNewFile,BufReadPost *.md set filetype=markdown
"let g:markdown_fenced_languages = ['html', 'javascript', 'yaml', 'yml', 'coffee', 'json', 'diff', 'python', 'bash=sh', 'latex=tex', 'bibtex=bib', 'ruby=rb']
"let g:markdown_minlines = 100
"au FileType markdown setlocal textwidth=80


" Jekyll Front Matter Syntax Highlighting Fix
au BufNewFile,BufRead,BufWrite *.md syntax match Comment /\%^---\_.\{-}---$/
let g:jekyll_path="/Users/Em/Repos/Page/pathologicalhandwaving.github.io"




" VIMHOME
if !$VIMHOME
  let $VIMHOME=$HOME."/.vim"
endif

if has('termguicolors')
  set termguicolors
  colorscheme gruvbox
endif



" SOURCES
source $VIMHOME/filetype.vim
source $VIMHOME/pack/settings/YUNOcommit.vim
source $VIMHOME/pack/settings/airline.vim
source $VIMHOME/pack/settings/mappings.vim
source $VIMHOME/pack/settings/highlights.vim
source $VIMHOME/pack/settings/templates.vim
source $VIMHOME/pack/settings/startify.vim
source $VIMHOME/pack/settings/highlights.vim
source $VIMHOME/pack/settings/clock.vim
source $VIMHOME/pack/settings/goyo.vim
source $VIMHOME/pack/settings/limelight.vim
source $VIMHOME/pack/settings/searchtasks.vim
source $VIMHOME/pack/settings/table.vim
source $VIMHOME/pack/settings/solarized.vim
source $VIMHOME/pack/settings/ultisnips.vim
source $VIMHOME/pack/plugins/start/StripWhiteSpaces/plugin/StripWhiteSpaces.vim
"source $VIMHOME/pack/plugins/start/dash.vim
"source $VIMHOME/pack/plugins/start/vim-airline-gruvbox-git
source $VIMHOME/pack/plugins/start/tabular/plugin/Tabular.vim
source $VIMHOME/pack/plugins/start/vim-airline-tomato/autoload/tomato.vim

" DICTIONARY
set dictionary+='/Users/Em/.vim/dictionaries'

" WILDMENU
set wildmenu
set wildmode=list:longest,full

" MOUSE
if has('mouse')
  set mouse=a
endif

" SEARCH
set incsearch


" STATUSBAR
set laststatus=2

let g:airline_theme='gruvbox'
" Airline Stuff
"let g:airline_left_sep = '🚀 '
let g:airline_left_sep = ' 🐹 '
let g:airline_right_sep = ' 🐹 '
"let g:airline_right_sep = '⏰ '

" Airline Tomato
let g:tomato#interval=47*60
let g:tomato#rest_time=17*60
let g:tomato#remind=' 🍅 '
let g:tomato#restinfo=' 🍅 '
let g:tomato#show_clock=1
let g:tomato#show_count_down=1



" Align GitHub-flavored Markdown tables
au FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>

" vimtex
source $VIMHOME/pack/settings/vimtex.vim
" ensure tex is latex not plaintext
let g:tex_flavor='latex'


