#+TAGS: DEFINITION
#+CATEGORY: DICTIONARY

* Literate Programming

Literate programming was first described by Donald Knuth\cite{Knuth1984} in 1984. The simplest explanation is that one would write expository text interspersed with code and macros which produced source code which is human and machine readable in as naturally human a way as possible.

That is, the source code has the properties of:
  - being self-documenting
  - readable by humans as text
  - executable by machines


** Use of macros

Macros act as an overlay hiding abstractions and source code in the text from the reader.

** Programming advantage

One of the advantages of writing programs in this way is to allow the writer to express the program's logic with a flow following more naturally human methods of description. One benefit of mirroring human flows of thought is that what should happen is clearer to the writer and so also clearer to the compiler.


** Reference Links

  - https://www-cs-faculty.stanford.edu/~knuth/lp.html
  - https://web.archive.org/web/20170603045917/http://vasc.ri.cmu.edu:80/old_help/Programming/Literate/literate.html
