(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons-scale-factor 1.0)
 '(auto-insert-directory "~/.emacs.d/snippets/autoinsert/")
 '(bib-auto-capitalize nil)
 '(bib-file "/Users/Em/Repos/ImInSpace/Library/Refs/default.bib")
 '(bibtex-file-path /Users/Em/Repos/ImInSpace/Library/Refs/)
 '(bibtex-files
   '("/Users/Em/Repos/ImInSpace/Library/Refs/default.bib" "/Users/Em/Repos/ImInSpace/Library/Refs/unread.bib"))
 '(custom-safe-themes
   '("4e21fb654406f11ab2a628c47c1cbe53bab645d32f2c807ee2295436f09103c6" "d6922c974e8a78378eacb01414183ce32bc8dbf2de78aabcc6ad8172547cb074" "aa0a998c0aa672156f19a1e1a3fb212cdc10338fb50063332a0df1646eb5dfea" "c74e83f8aa4c78a121b52146eadb792c9facc5b1f02c917e3dbb454fca931223" "a24c5b3c12d147da6cef80938dca1223b7c7f70f2f382b26308eba014dc4833a" default))
 '(ohai-personal-taste/paredit nil)
 '(ohai-personal-taste/run-wizard nil)
 '(ohai-personal-taste/splash 'daily-otter)
 '(ohai-personal-taste/style 'dark)
 '(ohai-personal-taste/training-wheels nil)
 '(ohai-personal-taste/window-state 'maximised)
 '(ohai/modules
   '(ohai-appearance ohai-fonts ohai-general ohai-splash ohai-ido ohai-navigation ohai-editing ohai-complete ohai-snippets ohai-codestyle ohai-dired ohai-project ohai-flycheck ohai-git ohai-orgmode ohai-help ohai-elisp ohai-helm ohai-eshell ohai-unicode ohai-refactor ohai-emoji ohai-smart-mode-line ohai-ext-window-nav ohai-lsp ohai-html ohai-markdown ohai-javascript ohai-js-web-mode ohai-flow ohai-purescript ohai-clojure ohai-erlang ohai-elixir ohai-haskell ohai-rust))
 '(org-agenda-diary-file "/Users/Em/Repos/ImInSpace/CaptainsLog/captainslog.org")
 '(org-agenda-files '("/Users/Em/Repos/ImInSpace/CaptainsLog/agenda.org"))
 '(org-columns-default-format "%25ITEM %3PRIORITY %TODO %15CATEGORY %TAGS")
 '(org-columns-ellipses "  .")
 '(org-complete-tags-always-offer-all-agenda-tags t)
 '(org-custom-properties
   '("REFERENCE" "REFTYPE" "SOURCE" "LIST" "PURPOSE" "DETAILS" "DATE_ADDED" "PROJECTID" "ACTIVITY" "ACTION"))
 '(org-deadline-warning-days 15)
 '(org-default-notes-file "~/Repos/ImInSpace/Notes/notes.org")
 '(org-directory "~/Repos/ImInSpace/")
 '(org-global-properties nil)
 '(org-log-note-headings
   '((done . "CLOSING NOTE: %T")
     (state . "State %-12s from %-12S %T")
     (note . "Note Added: %T")
     (reschedule . "Rescheduled from %S on %T")
     (delschedule . "Canceled from %S on %T")
     (redeadline . "Deadline Changed %S on %T")
     (deldeadline . "Canceled Deadline from %S on %T")
     (refile . "Date Refiled: %T")
     (clock-out . "Clocked Out: %T")))
 '(org-log-redeadline 'note)
 '(org-log-refile 'note)
 '(org-log-reschedule 'note)
 '(org-mobile-directory "/Users/Em/Repos/ImInSpace/ToGo/")
 '(org-mobile-inbox-for-pull "~/Repos/ImInSpace/ToGo/togo-refiler.org")
 '(org-startup-align-all-tables t)
 '(org-startup-with-inline-images t)
 '(org-startup-with-latex-preview t)
 '(org-tag-alist
   '(("CAPTAINSLOG")
     ("DICTIONARY")
     ("IMAGE")
     ("REFERENCE")
     ("LIST")
     ("REFNOTES")
     ("READLATER")
     ("QUOTE")
     ("GLOSSARY")
     ("ANTIGLOSSARY")
     ("ENTRY")
     ("LOGS")
     ("MATHS")
     ("SCRAPED")
     ("BLOG")
     ("EXOCORTEX")
     ("HOMEBASE")
     ("NOTES")
     ("TOGO")
     ("TOOLS")
     ("READING")))
 '(org-tags-column -42)
 '(org-time-stamp-custom-formats '("<%y/%m/%d %a>" . "<%y/%m/%d %a %H:%M>"))
 '(org-todo-keywords
   '((sequence "TODO" "DONE" "HOLD" "INPROGRESS" "PLAN" "FOLLOWUP")))
 '(org-treat-insert-todo-heading-as-state-change t)
 '(org-use-sub-superscripts '{})
 '(package-selected-packages
   '(cyberpunk-theme toc-org pdf-tools ereader latexdiff magic-latex-buffer edit-indirect-region-latex latex-preview-pane cdlatex auctex-latexmk auctex rainbow-identifiers rainbow-delimiters doom-themes neotree all-the-icons lsp-rust cargo rust-mode intero alchemist elixir-mode erlang clojure-mode psc-ide psci purescript-mode flow-mode lsp-javascript-typescript tern js2-refactor js2-mode json-mode rainbow-mode web-mode lsp-ui company-lsp lsp-mode smart-mode-line rich-minority emojify emr unicode-fonts fish-completion bash-completion esh-autosuggest eshell-git-prompt helm-ext helm-flx helm-projectile helm-flycheck swiper-helm helm eros highlight-parentheses discover-my-major which-key org-cliplink org-bullets org-plus-contrib git-gutter-fringe gist magit flycheck-color-mode-line flycheck ibuffer-projectile projectile dired+ ethan-wspace yasnippet company-try-hard company-emoji company-quickhelp company volatile-highlights shrink-whitespace expand-region multiple-cursors anzu ace-window avy flx-ido ido-vertical-mode smex ido-ubiquitous web material-theme diminish nyan-mode hlinum exec-path-from-shell f use-package paradox))
 '(refer-bib-directory '("/Users/Em/Repos/ImInSpace/Library/Refs/"))
 '(unread-bib-file "/Users/Em/Repos/ImInSpace/Library/Refs/unread.bib"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(outline-1 ((t (:inherit nil :foreground "SteelBlue1"))))
 '(outline-2 ((t (:inherit nil :foreground "SpringGreen1"))))
 '(outline-3 ((t (:inherit nil :foreground "PaleVioletRed1"))))
 '(outline-4 ((t (:inherit nil :foreground "MediumPurple1"))))
 '(outline-5 ((t (:inherit nil :foreground "LightBlue2"))))
 '(outline-6 ((t (:inherit nil :foreground "aquamarine1"))))
 '(outline-7 ((t (:inherit nil :foreground "RosyBrown2"))))
 '(outline-8 ((t (:inherit nil :foreground "SlateGray2"))))
 '(table-cell ((t (:background "slate gray" :foreground "LightCyan1" :inverse-video nil)))))
