;;; color-settings.el

(require 'org)

(setq org-todo-keyword-faces
    '(("PROJECT" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("TODO" :background "red1" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("PAUSED" :background "thistle4" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("STARTED" :background "DarkOrange" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("WAITING" :background "RosyBrown3" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("DELEGATED" :background "thistle4" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("REMEMBER" :background "tomato2" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("MAYBE" :background "pink4" :foreground "black" :weight bold :box (:line-width 2 :style none))
      ("APPOINTMENT" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("DONE" :background "forest green" :weight bold :box (:line-width 2 :style none))
      ("CANCELLED" :foreground "thistle4" :weight regular :strike-through)
      ("NEXT" :background "chartreuse2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("NOTE" :background "yellow2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("NOTED" :background "thistle4" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("EMAIL" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("MESSAGE" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("CALL" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("COMM" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("SCHEDULED" :background "OrangeRed3" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("RESCHEDULED" :background "OrangeRed1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("MEETING" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("EVENT" :background "DeepPink2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("LOOKUPLATER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 2 :style none ))
      ("WATCHLATER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("READLATER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 2 :style none ))
      ("LISTEN" :background "cyan4" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("DOWNLOAD" :background "cyan4" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("DEFINITION" :background "Cornflowerblue" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("COMMENT" :background "thistle4" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("CONVENTION" :background "SlateBlue3" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("LOG" :background "SlateBlue2" :foreground "black" :weight regular :box (:line-width 2 :style non))
      ("LOGGED" :foreground "thistle4" :weight regular :strike-through)
      ("INIT" :background "green2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("DECOMP" :background "tomato2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("CHECK" :background "yellow" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("CHECKED" :foreground "thistle4" :weight regular :strike-through)
      ("GET" :background "DarkOrange" :foreground "black":weight regular :box (:line-width 2 :style none))
      ("VOICEMEMO" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("COUNT" :background "forest green" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("COUNTED" :foreground "thistle4" :weight regular :strike-through)
      ("ORDER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("HABIT" :background "DarkOrange2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("REPEAT" :background "DarkOrange2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("MONDAY" :background "red1" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("TUESDAY" :background "orange" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("WEDNESDAY" :background "yellow" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("THURSDAY" :background "green" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("FRIDAY" :background "cyan2" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("SATURDAY" :background "blue" :foreground "black" :weight regular :box (:line-width 2 :style none))
      ("SUNDAY" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 2 :style none))))

(provide 'color-settings)
;;; color-settings.el ends here
