;;; color-settings.el

(require 'org)

(setq org-todo-keyword-faces
      '(("PROJECT" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PROJECT_LOG" :background "SlateBlue4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CHECK" :background "DarkOrange2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("HOLD" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("NEW_FILE" :background "green" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("STARTED" :background "forest green" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PAUSED" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CANCELLED" :background "black" :foreground "SlateGray4" :weight regular (:strike-through t))
        ("REFILE" :background "chartreuse1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REFILED" :foreground "SlateGray4" :weight regular (:strike-through t))
        ("DEFINITION" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("TOOL" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CLIP" :background "yellow" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("INPROGRESS" :background "DarkOrange2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("FOLLOWUP" :background "yellow2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PURGATORY" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("BLOCKED" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PAUSED" :background "DarkOrange1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("DEFERRED" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("TIMESTAMP" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("DEADLINE" :background "red1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("ACCOUNT" :background "SlateBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("WORK" :background "OrangeRed2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("MEETING" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REQUEST" :background "yellow" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REVIEW" :background "tomato2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CHECKPOINT" :background "DarkOrange2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("LAB" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("METHOD" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PROCEDURE" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PROTOCOL" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("EXPERIMENT" :background "DarkViolet" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("SIGNED" :background "OrangeRed3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PROJECT" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("WAITING" :background "chartreuse2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REPO" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("ACTIVATED" :background "chartreuse2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("ACTIVE" :background "chartreuse2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("INACTIVE" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("DEACTIVATED" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("AUDIT" :background "chartreuse1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("SHIFT" :background "chartreuse1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("TASK" :background "DarkOrange1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CHECK" :background "yellow2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("GET" :background "yellow3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("INSPECT" :background "chartreuse1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REPEAT" :background "forest green" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("HABIT" :background "forest green" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("DAY" :background "SlateBlue3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("WEEK_NO" :background "SlateBlue3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("MONTH" :background "SlateBlue3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("YEAR" :background "SlateBlue3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("ANNIVERSARY" :background "DeepPink2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("BIRTHDAY" :background "DeepPink2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("HOLIDAY" :background "DeepPink2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("QUESTION" :background "forest green" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("ANSWER" :background "DarkOrange" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("TODO" :background "red1" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("CONTACT" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PAUSED" :background "SlateGray4" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("STARTED" :background "DarkOrange" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("WAITING" :background "RosyBrown3" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("DELEGATED" :background "SlateGray4" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("REMEMBER" :background "tomato2" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("MAYBE" :background "pink4" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("APPOINTMENT" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("RECIPE" :background "#FB5543" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PACKAGE" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CANCELLED" :foreground "SlateGray4" :weight regular (:strike-through t))
        ("NEXT" :background "chartreuse2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("NOTE" :background "yellow2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("NOTED" :background "SlateGray4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("EMAIL" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("MESSAGE" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CALL" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("COMM_LOG" :background "DeepSkyBlue1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("SCHEDULED" :background "OrangeRed3" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("RESCHEDULED" :background "OrangeRed1" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("MEETING" :background "CornflowerBlue" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("EVENT" :background "DeepPink2" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("LOOKUPLATER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 1 :style none ))
        ("WATCHLATER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("READLATER" :background "cyan4" :foreground "black" :weight regular :box (:line-width 1 :style none ))
        ("LISTEN" :background "cyan4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("PODCAST" :background "cyan3" :foreground "black":weight regular :box (:line-width 1 :style none))
        ("DOWNLOAD" :background "cyan4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("AUDIOBOOK" :background "cyan4" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("DEFINITION" :background "#51AFEF" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("COMMENT" :background "yellow" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("CONVENTION" :background "#6495DD" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("LOG" :background "#575555" :foreground "black" :weight regular :box (:line-width 1 :style non))
        ("LOGGED" :background "#6C7B8B" :weight regular (:strike-through t))
        ("INIT" :background "#8BD49C" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("DECOMP" :background "#FB5543" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CHECK" :background "#3B9B35" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CHECKED" :background "#6C7B8B" :weight regular (:strike-through t))
        ("BILL" :background "#417630" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("LAB" :background "#6495DD" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("COUNT" :background "#216C2A" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("COUNTED" :background "#6C7B8B" :weight regular (:strike-through t))
        ("ORDER" :background "#6495DD" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("HABIT" :background "#3B9B35" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REPEAT" :background "#8BD49C" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("MONDAY" :background "#FF6655" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("TUESDAY" :background "#EBBF83" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("WEDNESDAY" :background "#EAEE80" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("THURSDAY" :background "#8BD49C" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("FRIDAY" :background "#46D9FF" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("SATURDAY" :background "#51AFEF" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("SUNDAY" :background "#C678DD" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("ISSUE" :background "#FB5543" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("FIXME" :background "#FB5543" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("FIXED" :background "#6C7B8B" :strike-through :weight regular (:strike-through t))
        ("RESOLVED" :background "#6C7B8B" :foreground "black" :weight regular (:strike-through t))
        ("IMPORTANT" :background "#D64459" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("INCIDENT" :backgound "#FB5543" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("REPORT" :background "#D64459" :foreground "black" :weight bold)
        ("CLOSED" :background "#6C7B8B" :weight normal (:strike-through t))
        ("REPORT" :background "#F07605" :foreground "black" :weight bold)
        ("CODE" :background "#002596" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("RATE_CODE" :background "#77B800" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("PRINT" :foreground "#CFE1F4" :weight bold)
        ("INNFLOW" :background "#0072CF" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("CASHIERING" :background "#417630" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("OUT_OF_ORDER" :background "#7E696D" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("MAINTENANCE" :background "#F07605" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("ROUTING" :background "#3B9B35" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("SEGMENTATION" :background "#0072CF" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("DAILY_ACTIVITY" :background "#0072CF" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("MOD" :background "#002596" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("EOD" :background "#0072CF" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("ROOM" :background "#0072CF" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("REVENUE" :background "green3" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("NONREVENUE" :background "#417630" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("DIRECT_BILL" :background "#417630" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("LEDGER" :background "#417630" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("ERRAND" :background "#8BD49C" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("PAYMENT" :background "#417630" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("BALANCE" :background "#417630" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("ISSUE_PHOTO" :background "#FB5444" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("VOICEMEMO" :background "#5EC4FF" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("CLOCK_IN" :background "#9EADA3" :foreground "black" :weight normal :box (:linewidth 1 :style none))
        ("CLOCK_OUT" :background "#A49494" :foreground "black" :weight normal :box (:linewidth 1 :style none))
        ("LOGIN" :background "#A49494" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("LOGOUT" :background "#9EADA3" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("DEPOSIT" :background "#A49494" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("BUY" :background "#FF6655" :foreground "black" :weight normal (:line-width 1 :style none))
        ("UPDATE" :background "#EEE000" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("OPEN" :background "#8FF333" :foreground "black" :weight normal  :box (:line-width 1 :style none))
        ("QUESTION" :background "SteelBlue" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("ANSWER" :background "aquamarine" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("DISCREPANCY" :background "#EBBF83" :foreground "black" :weight bold :box (:line-width 1 :style none))
        ("EVENTUALLY" :background "#444444" :foreground "black" :weight normal :slant italic)
        ("OVERDUE" :background "firebrick" :foreground "black" :weight bold :slant italic :box (:line-width 1 :style none))
        ("URGENT" :background "#D95468" :foreground "black" :weight bold :slant italic :box (:line-width 1 :style none))
        ("SpaceBot" :background "#660094" :foreground "black" :weight normal)
        ("WAITING" :background "#6C78B8" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("LabBot" :background "#6495DD" :foreground "black" :weight bold)
        ("CITEKEY" :foreground "#0072CF" :weight bold)
        ("SCRAPED" :background "purple" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("BOOK NOTES" :background "#EBBF83" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("CLIP" :background "#6495DD" :foreground "black" :weight regular :box (:line-width 1 :style none))
        ("QUOTE" :background "DarkViolet" :background "black" :weight regular :box (:line-width 1 :style none))
        ("Monopoly" :background "#216C2A" :foreground "black" :weight bold)
        ("BILL" :background "#216C2A" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("PAYMENT" :background "#216C2A" :foreground "black" :weight normal :box (:line-width 1 :style none))
        ("LibrarianBot" :background "#2F4F4F" :foreground "black" :weight bold)
        ("AudioBot" :background "#C678DD" :foreground "black" :weight bold)
        ("Captain's Log" :background "#575555" :foreground "black" :weight bold)
        ("EX1L3" :background "#5699AF" :foreground "black" :weight bold)
        ("LessonsLearned" :background "#41858C" :foreground "black" :weight bold)
        ("SwedishChef" :background "firebrick" :foreground "black" :weight bold)
        ("TeXBot" :background "SteelBlue" :foreground "black" :weight bold)
        ("WerX" :background "#3B9B35" :foreground "black" :weight bold)
        ("HolidayInn" :background "#3B9B35" :foreground "black" :weight bold)
        ("HOLIDAYINN" :background "#3B9B35" :foreground "black" :weight normal)
        ("DONE" :foreground "#6C7B8B" :weight normal (:strike-through t))
        ("DUE_DATE" :foreground "#FF6655" :foregroud "black" :weight regular :box (:line-width 1 :style none))
        ("FILED" :foreground "#6C7B8B" :weight normal (:strike-through t))))


(setq org-fontify-done-headline t)
(set-face-attribute 'org-done nil
                    :foreground "#6C7B8B"
                    :strike-through t)
(set-face-attribute 'org-headline-done nil
                    :foreground "#6C7B8B"
                    :strike-through t)


;;(defun my/modify-org-done-face ()
;;  (setq org-fontify-done-headline t)
;;  (set-face-attribute 'org-done nil :strike-through t)
;;  (set-face-attribute 'org-headline-done nil
;;                      :strike-through t
;;                      :foreground "SlateGray4"))

;;(eval-after-load "org"
;;  (add-hook 'org-add-hook 'my/modify-org-done-face))


(provide 'color-settings)
(message "Color Settings Loaded!")
;;; color-settings.el ends here
