;;; tag-settings.el
(require 'org)


;;; Code:

(setq org-tag-persistent-alist
      '((:startgroup . nil)
        ("ISSUE" . ?i)
        ("DEV" . ?d)
        ("MAINTENANCE" . ?a)
        ("BUG" . ?b)
        (:endgroup . nil)
        (:startgroup . nil)
        ("EASY" . ?e)
        ("MODERATE" . ?m)
        ("HARD" . ?r)
        ("UNDECIDABLE" . ?u)
        (:endgroup . nil)
        (:startgroup . nil)
        ("NOTE" . ?n)
        (:endgroup . nil)
        (:startgroup . nil)
        ("DICTIONARY" . ?y)
        ("DEFINITION" . ?g)
        (:endgroup . nil)))

(setq org-tag-faces
      '(("HomeBase" . (:foreground "forest green" :weight regular))
        ("TUTORIAL" . (:foreground "DeepPink2" :weight regular))
        ("CALL" . (:foreground "OrangeRed" :weight regular))
        ("PAYMENT" . (:foreground "#85bb65" :weight regular))
        ("PAID" . (:foreground "SlateGray4" :weight regular))
        ("GLOSSARY" . (:foreground "SlateGray4" :weight regular))
        ("DICTIONARY" . (:foreground "SkyBlue4" :weight regular))
        ("DEFINITION" . (:foreground "SkyBlue4" :weight regular))
        ("HOLIDAYINN" . (:foreground "chartreuse" :weight regular))
        ("AUDIT" . (:foreground "SkyBlue3" :weight regular))
        ("CAR" . (:foreground "#000066" :weight regular))
        ("MOD" . (:foreground "cyan3" :weight regular))
        ("ISSUE" . (:foreground "red" :weight regular))
        ("REPORT" . (:foreground "BlueViolet" :weight regular))
        ("WORK" . (:foreground "gold" :weight regular))
        ("TUTORING" . (:foreground "IndianRed" :weight regular))
        ("STUDY" . (:foreground "DeepPink2" :weight regular))
        ("LAB" . (:foreground "LightSeaGreen" :weight regular))
        ("SCHEDULE" . (:foreground "OrangeRed" :weight regular))
        ("DUE" . (:foreground "red1" :weight bold))
        ("PLANNING" . (:foreground "DarkOrange2" :weight regular))
        ("INPROGRESS" . (:foreground "DarkOrange2" :weight regular))
        ("SwedishChef" . (:foreground "OrangeRed" :weight regular))
        ("ACCOUNT" . (:foreground "LightSeaGreen" :weight regular))
        ("DEV" . (:foreground "SkyBlue1" :weight regular))
        ("MAINTENANCE" . (:foreground "PaleVioletRed" :weight regular))
        ("BUG" . (:foreground "OrangeRed" :weight regular ))
        ("EASY" . (:foreground "green" :weight regular))
        ("MODERATE" . (:foreground "yellow" :weight regular))
        ("HARD" . (:foreground "DarkOrange2" :weight regular))
        ("UNDECIDABLE" . (:foreground "red" :weight bold))
        ("URGENT" . (:foreground "OrangeRed" :weight bold))
        ("ShipBot" . (:foreground "IndianRed4" :weight regular))
        ("LabBot" . (:foreground "SkyBlue2" :weight regular))
        ("HomeBase" . (:foreground "forest green" :weight regular))
        ("APARTMENT" . (:foreground "DarkOrange3" :weight regular))
        ("TeXBot" . (:foreground "DarkViolet" :weight regular))
        ("LaTeX" . (:foreground "DarkViolet" :weight regular))
        ("WAITING" . (:foreground "green" :weight regular))
        ("REFILE" . (:foreground "green" :weight regular))
        ("LibrarianBot" (:foreground "burlywood" :weight regular))
        ("MonopolyBot" . (:foreground "#85bb65" :weight regular))
        ("SpaceBot" . (:foreground "#000080" :weight regular))
        ("DocsBot" . (:foreground "AliceBlue" :weight regular))
        ("AudioBot" . (:foreground "HotPink" :weight regular))
        ("WerX" . (:foreground "#0072cf" :weight regular))
        ("AutoBot" . (:foreground "#2F4F4F" :weight regular))
        ("TODO" . (:foreground "OrangeRed" :weight regular))
        ("READLATER" . (:foreground "burlywood" :weight regular))
        ("LOG" . (:foreground "SlateGray4" :weight regular))
        ("NOTE" . (:foreground "gold" :weight regular))
        ("RECIPE" . (:foreground "DarkOrange2" :weight regular))
        ("DEFINITION" . (:foreground "burlywood" :weight regular))
        ("PACKAGE" . (:foreground "CornflowerBlue" :weight regular))))

(setq org-fast-tag-selection-single-key t)


;; Logging States
(setq org-log-done (quote time))
(setq org-log-redeadline (quote time))
(setq org-log-reschedule (quote time))


(setq org-treat-S-cursor-todo-selection-as-state-change t)

(provide 'tag-settings)
(message "Tag Settings Loaded!")
;;; tag-settings.el ends here
