let g:task_report_name = 'next'
let g:task_report_comand = []
let g:task_default_prompt =['due', 'description', 'project', 'context']
let g:task_info_vsplit = 0
let g:task_info_position = 'belowright'
let g:task_info_size = 15
let g:task_log_directory = '~/.task'
let g:task_right_arrow = '⤇  '
let g:task_left_arrow = ' ⤆ '
