install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
    sudo apt-get -qq update &&
    sudo apt-get -qq -f install &&
    sudo apt-get -qq install emacs-snapshot

script:
  - ln -s . .emacs.d &&
    HOME=`pwd` emacs --batch -Q --eval "(load-file \"ohai/ohai-test.el\")"
